### ISSUE TITLE
triggers.py carregar variáveis do vars.conf

### ISSUE THREAD

**Issue by rauhmaru** [rauhmaru/telegram-scripts#6]
As variáveis utilizadas nos scripts devem ser carregadas via o arquivo vars.conf.

**Comment by janssenlima** [comment]
Verificando.

**Comment by janssenlima** [comment]
Seria possível criar uma pasta conf para armazenar o vars.conf?
Assim, nos códigos Python iríamos carregar essas configurações por pacotes. Evitaria fazer "gambiarras".

**Comment by janssenlima** [comment]
Resolvido com a criação de pacote Python usando o diretório conf. O arquivo de configuração foi renomeado de vars.conf para vars.py. Com esse ajuste, todo e qualquer tipo de configuração deverá ser armazenada no diretório criado.
